name: Laravel Deploy to Hostinger

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, bcmath, pdo_mysql, fileinfo

      - name: Install Composer dependencies
        run: composer update --no-dev --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Build frontend (if using Vite)
        run: |
          if [ -f package.json ]; then
            npm install
            npm run build
          fi

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOSTINGER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HOSTINGER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Hostinger Server
        run: |
          rsync -avz --delete \
          --exclude ".git" \
          --exclude ".github" \
          --exclude "node_modules" \
          --exclude "tests" \
          ./ ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}:${{ secrets.HOSTINGER_PATH }}

      - name: Run Laravel commands on server
        run: |
          ssh ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }} "
          cd ${{ secrets.HOSTINGER_PATH }} &&
          composer update &&
          php artisan migrate --force &&
          php artisan optimize
          "
